#!/bin/sh /etc/rc.common

# 服务启动优先级
START=20

# 停止优先级
STOP=15

# 使用 Procd 守护进程管理服务
USE_PROCD=1

# 额外命令支持：允许通过命令 `service <name> version` 查看插件版本
if type extra_command 1>/dev/null 2>&1; then
  extra_command 'version' 'Show version information'
fi

# 定义插件版本信息及程序二进制文件路径
readonly PKG_NAME='PKG_NAME'
readonly PKG_VERSION='PKG_VERSION'
readonly PKG_BIN="/usr/sbin/$PKG_NAME"

# 防止重复执行繁重任务
on_boot_flag=false

# 重定向错误输出，防止频繁启停服务时产生大量无用的报错日志
__UBUS_BIN="$(command -v ubus || echo /bin/ubus)"

ubus() {
  if [ "$1" = 'call' ] && [ "$2" = 'service' ] && [ "$3" = 'delete' ]; then
    "$__UBUS_BIN" "$@" >/dev/null 2>&1 || true
  else
    "$__UBUS_BIN" "$@"
  fi
}

# 拼接启动参数
append_arg() { cmdarg="$cmdarg $1"; }

# 将布尔配置转为参数
append_flag() {
  local section="$1" option="$2" switch="$3" default="${4:-0}" value
  config_get_bool value "$section" "$option" "$default"
  [ "$value" -ne 0 ] && append_arg "$switch"
}

# 将参数转为命令参数
append_parm () {
  local section="$1" option="$2" switch="$3" default="$4" skip_value="$5" value
  config_get value "$section" "$option" "$default"
  [ -n "$value" ] && [ "$value" != "$skip_value" ] && append_arg "$switch $value"
}

# 核心业务逻辑
start_instance() {
  local config="$1" param="$2" cmdarg

  procd_open_instance
  procd_set_param command $PKG_NAME $cmdarg
  procd_set_param respawn 3600 5 5
  procd_set_param stderr 1
  procd_set_param stdout 1
  # procd_open_data
  # procd_close_data
  procd_close_instance
}

# 启动服务
start_service() {
}

# 停止服务
stop_service() {
}

# 启动完成后的回调
service_started() {
}

# 停止完成后的回调
service_stopped() {
}

# 配置变更自动重启
service_triggers() {
}

# service restart 重定向到 reload，procd 会自动处理重载逻辑
restart() { reload "$@"; }

# 开机引导入口，通过 rc_procd 启动服务
boot() { rc_procd start_service 'on_boot' && service_started 'on_boot'; }

# 输出版本号
version() { echo "$PKG_VERSION"; }
